name: link_preview
description: This is a URL preview plugin that previews the content of a URL.
version: 0.1.0
author: Jamal Shr
homepage: https://github.com/shrjamal/link_preview

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.4.1
  gbk2utf8: ^1.0.1
  html: ^0.14.0+4
  http: ^0.12.2
  linkify: ^3.0.0
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10

dev_dependencies:
  effective_dart: ^1.3.0
